# Generated by Django 6.1 on 2026-08-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='term',
            field=models.CharField(choices=[('short', 'Short-term'), ('long', 'Long-term')], default='short', max_length=5),
        ),
    ]
