# Generated by Django 6.1 on 2026-08-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
