# Generated by Django 6.1 on 2026-08-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['scheduled_date', 'order']},
        ),
        migrations.AddField(
            model_name='quest',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
