# Generated by Django 6.1 on 2026-08-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_alter_quest_options_quest_is_enabled_quest_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('start_time', models.TimeField(default='09:30')),
                ('is_cleared', models.BooleanField(default=False)),
            ],
        ),
    ]
