# Generated by Django 6.0.6 on 2026-08-21 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_dayschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 30)),
        ),
    ]
