# Generated by Django 6.0.6 on 2026-08-21 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_alter_quest_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='reschedule_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 30)),
        ),
    ]
