# Generated by Django 6.1 on 2026-08-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_dayschedule_reschedule_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayschedule',
            name='reschedule_enabled',
        ),
    ]
