# Generated by Django 6.1 on 2026-08-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_remove_dayschedule_reschedule_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
    ]
