# Generated by Django 6.1 on 2026-08-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0007_quest_is_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='anchor_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
