# Generated by Django 6.1 on 2026-08-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0008_quest_anchor_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
