# Generated by Django 6.1 on 2026-08-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0009_dayschedule_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='day_started',
            field=models.BooleanField(default=False),
        ),
    ]
